---
- name: Grafana FreeIPA LDAP Konfigürasyonu
  hosts: grafana_servers
  become: yes

  tasks:
    - name: defaults.ini dosyasını düzenle
      blockinfile:
        path: /etc/grafana/defaults.ini
        block: |
          [auth.ldap]
          enabled = true
          config_file = /etc/grafana/ldap.toml
        marker: "# {mark} ANSIBLE MANAGED BLOCK"

    - name: ldap.toml dosyasını düzenle
      blockinfile:
        path: /etc/grafana/ldap.toml
        block: |
          [[servers]]
          host = "ldap.example.com"
          port = 389
          use_ssl = false
          start_tls = false
          ssl_skip_verify = false
          bind_dn = "cn=admin,dc=example,dc=com"
          bind_password = "admin_password"
          search_filter = "(cn=%s)"
          search_base_dns = ["dc=example,dc=com"]
          [servers.attributes]
          name = "givenName"
          surname = "sn"
          username = "uid"
          member_of = "memberOf"
          email = "mail"
        marker: "# {mark} ANSIBLE MANAGED BLOCK"
