---
- name: Grafana FreeIPA LDAP Konfigürasyonu
  hosts: grafana_servers
  become: yes

  tasks:
    - name: defaults.ini dosyasında [auth.ldap] bloğunu düzenle
      lineinfile:
        path: /etc/grafana/defaults.ini
        regexp: '^\[auth.ldap\].*$'
        line: '[auth.ldap]'
        backrefs: yes
      register: auth_ldap_changed
      changed_when: auth_ldap_changed.changed

    - name: defaults.ini dosyasında config_file değerini düzenle
      lineinfile:
        path: /etc/grafana/defaults.ini
        regexp: '^config_file = /etc/grafana/ldap.toml$'
        line: 'config_file = /etc/grafana/ldap.toml'
      register: config_file_changed
      changed_when: config_file_changed.changed
