---
- name: Grafana FreeIPA LDAP Konfigürasyonu
  hosts: grafana_servers
  become: yes

  tasks:
    - name: defaults.ini dosyasındaki [auth.ldap] bloğunu güncelle
      replace:
        path: /etc/grafana/defaults.ini
        regexp: '(^\[auth\.ldap\]$[\s\S]*?^enabled\s*=\s*).*$'
        replace: '\1true'
        backup: yes

    - name: defaults.ini dosyasındaki [auth.ldap] bloğunu güncelle
      replace:
        path: /etc/grafana/defaults.ini
        regexp: '(^\[auth\.ldap\]$[\s\S]*?^config_file\s*=\s*).*$'
        replace: '\1/etc/grafana/ldap.toml'
        backup: yes

    - name: defaults.ini dosyasındaki [auth.ldap] bloğunu güncelle
      replace:
        path: /etc/grafana/defaults.ini
        regexp: '(^\[auth\.ldap\]$[\s\S]*?^allow_sign_up\s*=\s*).*$'
        replace: '\1false'
        backup: yes
