[[servers]]
host = "ldap://<FreeIPA_Sunucu_IP>"
port = 389
use_ssl = false
start_tls = false
bind_dn = "uid=admin,cn=users,cn=accounts,dc=example,dc=com"
bind_password = "<admin_kullanıcı_parolası>"
search_filter = "(uid=%s)"
search_base_dns = ["cn=users,cn=accounts,dc=example,dc=com"]
